### ISSUE TITLE
CreateTable should be idempotent

### ISSUE THREAD

**Issue by acim** [cirello-io/pglock#32]
At the moment there is no way to find out if locks table exists or not, so it would be nice that this method actually first checks for existence of the table and then create it if not there. So it should not trigger an error if the table already exists.

If this is not acceptable for any reason then it would be nice to introduce a new method which checks for existence of the locks table. This way we could avoid errors in the logs even if we ignore it at CreateTable. Namely, if you turn on pgx logging, there will always be an error reported by pgx.

I could contribute this, but please let me know do you want me to modify CreateTable to make it idempotent or create a new method, let's say TableExists or something like that.

**Comment by ucirello** [comment]
> If you drop CreateTable then everyone has to create the table somehow else, either manually or by adding migration. 

And I think that's fine. It is for the consumer of this package to decide how the database should be operated, not the library itself. I added a piece of sugar that is being misused quite frequently. For some applications, hot DB changes might be fine, but for others it might not. `CreateTable` offers a tool that is hard to wield correctly.

> Even in that case the problem of changing the table schema would remain.

You are right. The problem remains but it would not be pglock's responsibility any longer. 

> The only automatic way would be to read the information_schema and find out if the table with correct schema is there or not.

And perhaps the more fundamental question is why it needs to be automatic in the first place.

> I see that this is quite difficult topic even though it looks easy.

I agree. And because of the Go 1 compatibility promise, I can't do a lot except trying to not make the situation any worse or much different than what it currently is.

**Comment by acim** [comment]
> You are right. The problem remains but it would not be pglock's responsibility any longer.

Well, in case you have to change the schema any time in the future, you just mark in the changelog that this is breaking change and eventually bump major version again. I mean it would be nice to inform users about this so that they can't miss it. :D

**Comment by ucirello** [comment]
>  you just mark in the changelog that this is breaking change and eventually bump major version.

Great idea actually!
